name: Deploy to WordPress.org
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

env:
  plugin_name: vk-all-in-one-expansion-unit

jobs:
  tag:
    name: Deploy to plugin directory
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: ls
      run: composer install --optimize-autoloader --prefer-dist --no-dev
      run: ls
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: vk-all-in-one-expansion-unit